# Generated by Django 5.2.10 on 2026-01-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Product',
        ),
    ]
